### ISSUE TITLE
Fix initial heading behavior in HolonomicDriveController

### ISSUE THREAD

**Issue by lidor51** [jsimpso81/FRC_LV_TrajLib#24]
Initial heading behavior in holonomic drive controller.
https://github.com/wpilibsuite/allwpilib/pull/3290

**Comment by jsimpso81** [comment]
Looking at other holonomic issues since 3163 it looks like https://github.com/wpilibsuite/allwpilib/pull/3176 should be incorporated as well.

**Comment by jsimpso81** [comment]
Okay 3176 Doesn't apply here.  Moved to separate issue.

**Comment by jsimpso81** [comment]
Resoloved
