### ISSUE TITLE
Implement WPILIB 2761 2762 quintic spline change

### ISSUE THREAD

**Issue by jsimpso81** [jsimpso81/FRC_LV_TrajLib#4]
Implement WPILIB 2761 2762 quintic spline change

https://github.com/wpilibsuite/allwpilib/issues/2761

https://github.com/wpilibsuite/allwpilib/issues/2762

**Comment by jsimpso81** [comment]
The utility programs that use this routine don't seem to be affected by this bug..  An error was added if the routine is not called with an array with an even number of members.

**Comment by lidor51** [comment]
What about https://github.com/wpilibsuite/allwpilib/issues/3291?

**Comment by jsimpso81** [comment]
It doesn't look to me that this is pushed to the main branch yet..  Did I miss it?

**Comment by jsimpso81** [comment]
implemented, tested.  Closed.
