### ISSUE TITLE
PathPlanner LoadPath fails with repeated error

### ISSUE THREAD

**Issue by MazeOfEncryption** [jsimpso81/FRC_LV_TrajLib#48]
I successfully got swerve drive odometry and kinematics working using this library. Now, I was attempting to use PathPlanner.
For some reason, whenever I try to load a path file, I get this error, repeatedly (I have to spam click enter and hit `CTRL + .` to stop it).
![image](https://user-images.githubusercontent.com/19843876/160030208-0bd87b1d-2ba6-4d73-860a-9be65fa9d8db.png)

I tried to determine what the cause of the error was by probing some of the subvi's (and temporarily setting them to non-reetrant).

Oddly enough, it seems that the file *is* being loaded and parsed successfully into an array of `PathPlannerWayPoints`. However, it seems that somewhere in the parsing of this trajectory, there's some sort of error. Any help would be appreciated!

**Comment by MazeOfEncryption** [comment]
Just figured out that it was caused by holonomic mode being enabled in PathPlanner. Everything seems to work with it disabled. 
![image](https://user-images.githubusercontent.com/19843876/160031080-c6a4f9ab-d39f-4f6f-8077-9fa455e13539.png)

**Comment by MazeOfEncryption** [comment]
Perhaps either add better error checking for this, or implement support for holonomic patholanner trajectories

**Comment by MazeOfEncryption** [comment]
Interestingly, it seems to work with holonomic paths now? I didn't change anything...

Not sure what was going on.

**Comment by jsimpso81** [comment]
This may be caused by a newer feature in pathplanner that hasn't been ported to LabVIEW yet.  I'll have to check on the latest pathplanner code for differences.  Thanks for posting the issue.

**Comment by jsimpso81** [comment]
This library is based on the 2022.0.0 release.  I'm implementing the updates.   After that Is done, I'd like to try and duplicate the problem.  Can you send the JSON file that causes the error?

**Comment by brandonzx3** [comment]
im getting this same error on a non holonomic path. not sure what to do

**Comment by jsimpso81** [comment]
Can you send me the file you are trying to read. Also there are some changes to the pathfinder Labview library that aren’t in a published build.  Some relatively recent fixes were made to the Java version and I just finished putting these to Labview.  I’ll make a build for you to try.  However having the file will help me diagnose.   Thanks.

**Comment by jsimpso81** [comment]
I think that this is fixed.   Some programmer....... left a debug pop up box in PathPlanner_Trajectory_CalculateMaxVel.vi
You can change it yourself, or a pre-release of the libraries is published with this fix...
https://github.com/jsimpso81/FRC_LV_TrajLib/releases/tag/V2.09Beta

Here is a project that I used for testing.  It runs on a PC..
[PathPlannerReadFileTest.zip](https://github.com/jsimpso81/FRC_LV_TrajLib/files/8691040/PathPlannerReadFileTest.zip)

Let me know if this works for you.

**Comment by brandonzx3** [comment]
sorry for the delay. the pre-release fixed this issue. thank you for the help.

**Comment by jsimpso81** [comment]
No troubles.   Glad its fixed.   Closed.
